### ISSUE TITLE
Bug Report_ 

### ISSUE THREAD

**Issue by narzk** [pitt-miskov-zivanov-lab/BioRECIPE#2]
Command: 
python run_sbml_biorecipe.py -i /Users/niloofararazkhani/Documents/BioRECIPE/examples/sbml/map_mapk.xml -o /Users/niloofararazkhani/Documents/BioRECIPE/examples/interaction_lists/interaction_biorecipe_test.xlsx
 
Error:
 
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

Line in code:
 
File "/Users/niloofararazkhani/Documents/BioRECIPE/translators/sbml/celldesigner2qual.py", line 1068, in write_biorecipes
    df = df.append({"Element Name": data["element name"], "Element IDs": species, "Element Type": data["type"], "Compartment": data["compartment"],
    
  Environment: Macbook, Python 3.8.18

**Comment by narzk** [comment]
BugReport_

command: python run_sbmlqual_biorecipe.py -i /Users/niloofararazkhani/Documents/BioRECIPE/examples/sbmlqual/Tcell_differentiation.sbml -o /Users/niloofararazkhani/Documents/BioRECIPE/examples/interaction_lists/Tcell_differentiation.xlsx

Error:
Traceback (most recent call last):
  File "run_sbmlqual_biorecipe.py", line 154, in <module>
    main()
  File "run_sbmlqual_biorecipe.py", line 150, in main
    sbmlqual_to_biorecipe(args.input, args.output)
  File "run_sbmlqual_biorecipe.py", line 135, in sbmlqual_to_biorecipe
    sbml_qual.sbmlqual_biorecipe(input, output)
  File "run_sbmlqual_biorecipe.py", line 48, in sbmlqual_biorecipe
    res = bs4.BeautifulSoup(open(input_file).read(), 'lxml')
  File "/Users/niloofararazkhani/.pyenv/versions/3.8.18/lib/python3.8/site-packages/bs4/__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?


Environment: Macbook, Python 3.8.18

**Comment by DifeiT** [comment]
For the first issue, it is caused by the version of pandas: https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append. To run sbmlqual -> biorecipe, you need to install the BeautifulSoup package to parse the xml file. I will upload a Requirements.txt soon.

**Comment by narzk** [comment]
> Command: python run_sbml_biorecipe.py -i /Users/niloofararazkhani/Documents/BioRECIPE/examples/sbml/map_mapk.xml -o /Users/niloofararazkhani/Documents/BioRECIPE/examples/interaction_lists/interaction_biorecipe_test.xlsx
> 
> Error:
> 
> AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
> 
> Line in code:
> 
> File "/Users/niloofararazkhani/Documents/BioRECIPE/translators/sbml/celldesigner2qual.py", line 1068, in write_biorecipes df = df.append({"Element Name": data["element name"], "Element IDs": species, "Element Type": data["type"], "Compartment": data["compartment"],
> 
> Environment: Macbook, Python 3.8.18

For this @DifeiT  I put _append instead of append for data frame and it worked for me. 
should I push the change?

**Comment by narzk** [comment]
> BugReport_
> 
> command: python run_sbmlqual_biorecipe.py -i /Users/niloofararazkhani/Documents/BioRECIPE/examples/sbmlqual/Tcell_differentiation.sbml -o /Users/niloofararazkhani/Documents/BioRECIPE/examples/interaction_lists/Tcell_differentiation.xlsx
> 
> Error: Traceback (most recent call last): File "run_sbmlqual_biorecipe.py", line 154, in main() File "run_sbmlqual_biorecipe.py", line 150, in main sbmlqual_to_biorecipe(args.input, args.output) File "run_sbmlqual_biorecipe.py", line 135, in sbmlqual_to_biorecipe sbml_qual.sbmlqual_biorecipe(input, output) File "run_sbmlqual_biorecipe.py", line 48, in sbmlqual_biorecipe res = bs4.BeautifulSoup(open(input_file).read(), 'lxml') File "/Users/niloofararazkhani/.pyenv/versions/3.8.18/lib/python3.8/site-packages/bs4/**init**.py", line 250, in **init** raise FeatureNotFound( bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
> 
> Environment: Macbook, Python 3.8.18

same port this part. I changed .append to ._append.
please tell me if it needs to be pushed
@DifeiT

**Comment by DifeiT** [comment]
Solved by using pandas 1.2.5, as 'append' was removed in pandas 2.0.
